services:
  redis:
    image: 'redis/redis-stack'
    ports:
      - '6379:6379'
      - '8001:8001'
    networks:
      - urlnet
  app:
    build:
      # context: ./nano_backend_service
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - '8000:8000'
    volumes:
      - './nano_backend_service:/app'
    depends_on:
      - redis
    networks:
      - urlnet
 
networks:
  urlnet: